### ISSUE TITLE
Plugin does not show errors as expected

### ISSUE THREAD

**Issue by alvassin** [gruntjs/grunt-contrib-less#12]
Today i found that some .less files were not builded, because there was syntax error:

``` css
.class {
 background: rgba (0,0,0,.5); /* space after rgba is syntax error */
}
```

Could you please make this plugin show errors? i've more fifty .less files for different components.. such plugin behaviour causes to spend lots of time...

Thanks in advance!
