### ISSUE TITLE
Variables not modified in all cases

### ISSUE THREAD

**Issue by paazmaya** [gruntjs/grunt-contrib-less#173]
I have a LESS file with:

``` css
@import-path: "/normal-place";
@import "@{import-path}/styles";
```

With the following configuration the variable is not overwritten:

``` js
modifyVars: {
  'import-path': "'../other-location'"
}
```

With the following configuration the variable is overwritten:

``` js
modifyVars: {
  'import-path': '../other-location'
}
```

but it comes out as, thus not working as supposed to:

``` css
@import-path: ../other-location;
```
