### ISSUE TITLE
banner not placed at top of file when using @import

### ISSUE THREAD

**Issue by boneskull** [gruntjs/grunt-contrib-less#263]
`@import` is (rightly) being treated as a special case: this statement will appear as the first line in the generated CSS file.

However, if a `banner` is specified, it's inserted even before that.

But as I understand, `@import` needn't come before *any* other lines in the `.css` file; it must simply come before other styles.  

#### Example

Given `.less`:

```css
@import url('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,700');
body {
  color: red;
}
```

And `banner` option:

```javascript
"/* it's a banner */"
```

The resulting `.css` file will look like:

```css
@import url('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,700');
/* it's a banner */
body {
  color: red;
}
```

This happens regardless of whether `compress` is set.
