### ISSUE TITLE
sourceMapURL with multiple output?

### ISSUE THREAD

**Issue by sparanoid** [gruntjs/grunt-contrib-less#285]
I have many .less files and I'd like to generate separated CSS all with sourcemap support.

My grunt:

```yml
    less:
      serve:
        options:
          sourceMap: true
          outputSourceFiles: true

        files: [
          expand: true
          cwd: "<%= config.assets %>/less/"
          src: ["**/*.less"]
          dest: "<%= config.assets %>/css/"
          ext: ".css"
        ]
```

Output:

```
├── less/
|   ├── dashboard.less
|   ├── doc.less
|   ├── doc-v2.less
|   ├── main.less
|   └── *.less
├── css/
|   ├── dashboard.css
|   ├── dashboard.css.map
|   ├── doc.css
|   ├── doc.css.map
|   ├── doc-v2.css
|   ├── doc-v2.css.map
|   ├── main.css
|   ├── main.css.map
|   ├── *.css
|   └── *.css.map
```

This doesn't work because the comments generated inside CSS are:

main.css:
```css
/*# sourceMappingURL=_app/assets/css/main.css.map */
```

doc.css:
```css
/*# sourceMappingURL=_app/assets/css/doc.css.map */
```

...

Chrome didn't recognize them so I have to define `sourceMapURL` but I can only pass one file to it:

```yml
options:
  sourceMap: true
  outputSourceFiles: true
  sourceMapURL: "main.css.map"
```

main.css:
```css
/*# sourceMappingURL=main.css.map */
```

doc.css:
```css
/*# sourceMappingURL=main.css.map */
```

...

So is there any way `sourceMapURL` can be set based on different file?

Thanks!
