### ISSUE TITLE
Compress doesn't work

### ISSUE THREAD

**Issue by Xeyos88** [gruntjs/grunt-contrib-less#331]
Hi,
compress option doesn't work for me.
i have this task in my gruntfile.js
```js
less: {
            server: {
                options: {
			compact : true,
			compress: true,
			yuicompress: true,
                	optimization: 2,
			ieCompat: true
                },
                files: {
                 'web/styles/css/style.css':'web/styles/less/style.less'
```
and i load npmTask grunt-contrib-less and run less:server in all env.
But the css generated is not compressed.

I have style.less(exemple):
```less
body{
background: red;
}
```
and the result is style.css
```css
body {
background: red;
}
```
