### ISSUE TITLE
dumpLineNumbers doesn't work with CSS keyframes

### ISSUE THREAD

**Issue by sparanoid** [gruntjs/grunt-contrib-less#57]
It converts them to:

``` css
@-webkit-keyframes spin {
  /* line 135, /local/path/to/my.less */
  @media -sass-debug-info{filename{font-family:file\:\/\/\/local\/path\/to\/my\.less}line{font-family:\00003135}}
  0% {
    -webkit-transform: rotateY(-180deg);
  }
  /* line 136, /Users/sparanoid/Git/sparanoid-start/app/assets/less/main.less */
  @media -sass-debug-info{filename{font-family:file\:\/\/\/local\/path\/to\/my\.less}line{font-family:\00003136}}
  100% {
    -webkit-transform: rotateY(0deg);
  }
}
```

Which Safari and Chrome don't treat it as a valid keyframes.
